<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>System Health Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #333;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2d3748;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .health-score {
            background: {{ $healthColor === 'green' ? '#48bb78' : ($healthColor === 'yellow' ? '#ecc94b' : '#f56565') }};
            color: white;
            padding: 20px;
            text-align: center;
            margin: 20px 0;
            border-radius: 8px;
        }
        .health-score h2 {
            margin: 0;
            font-size: 48px;
        }
        .health-score p {
            margin: 10px 0 0 0;
            font-size: 18px;
        }
        .section {
            margin: 30px 0;
            page-break-inside: avoid;
        }
        .section h3 {
            background: #f7fafc;
            padding: 10px;
            border-left: 4px solid #4299e1;
            margin: 0 0 15px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        table th {
            background: #edf2f7;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #cbd5e0;
        }
        table td {
            padding: 8px;
            border: 1px solid #e2e8f0;
        }
        .stat-grid {
            display: table;
            width: 100%;
            margin: 15px 0;
        }
        .stat-item {
            display: table-row;
        }
        .stat-label {
            display: table-cell;
            padding: 8px;
            font-weight: bold;
            width: 60%;
        }
        .stat-value {
            display: table-cell;
            padding: 8px;
            text-align: right;
            width: 40%;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 2px solid #e2e8f0;
            text-align: center;
            font-size: 10px;
            color: #718096;
        }
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-green { background: #c6f6d5; color: #22543d; }
        .badge-yellow { background: #fefcbf; color: #744210; }
        .badge-red { background: #fed7d7; color: #742a2a; }
    </style>
</head>
<body>
    {{-- Header --}}
    <div class="header">
        <h1>System Health Report</h1>
        <p><strong>{{ config('app.name', 'Darul Abrar Madrasa') }}</strong></p>
        <p>Generated: {{ $generatedAt }}</p>
        <p>Generated By: {{ $generatedBy }}</p>
    </div>

    {{-- Executive Summary --}}
    <div class="health-score">
        <h2>{{ number_format($healthScore, 1) }}%</h2>
        <p>System Health: {{ strtoupper($healthStatus) }}</p>
        @if($totalIssues > 0)
            <p style="margin-top: 10px;">{{ $totalIssues }} issue(s) detected</p>
        @else
            <p style="margin-top: 10px;">All systems operational</p>
        @endif
    </div>

    {{-- Key Metrics --}}
    <div class="section">
        <h3>Key Metrics</h3>
        <div class="stat-grid">
            <div class="stat-item">
                <div class="stat-label">Total Users</div>
                <div class="stat-value">{{ array_sum($usersByRole) }}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Missing Role Records</div>
                <div class="stat-value">{{ $totalMissing }}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Orphaned Records</div>
                <div class="stat-value">{{ $totalOrphaned }}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Spatie Sync Issues</div>
                <div class="stat-value">{{ $missingSpatieRoles->count() + $mismatchedSpatieRoles->count() }}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Migration Progress</div>
                <div class="stat-value">{{ number_format($migrationProgress, 1) }}%</div>
            </div>
        </div>
    </div>

    {{-- Data Integrity --}}
    @if($totalMissing > 0 || $totalOrphaned > 0)
    <div class="section">
        <h3>Data Integrity Issues</h3>
        
        @if($totalMissing > 0)
        <h4>Missing Role Records ({{ $totalMissing }})</h4>
        @foreach(['teacher', 'student', 'guardian', 'accountant'] as $role)
            @if($missingRoleRecords[$role]->count() > 0)
                <p><strong>{{ ucfirst($role) }}s:</strong> {{ $missingRoleRecords[$role]->count() }} missing</p>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($missingRoleRecords[$role]->take(20) as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->created_at->format('d M Y') }}</td>
                            </tr>
                        @endforeach
                        @if($missingRoleRecords[$role]->count() > 20)
                            <tr>
                                <td colspan="4" style="text-align: center; color: #666;">
                                    ... and {{ $missingRoleRecords[$role]->count() - 20 }} more (see dashboard for full list)
                                </td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            @endif
        @endforeach
        @endif

        @if($totalOrphaned > 0)
        <h4 style="margin-top: 20px;">Orphaned Records ({{ $totalOrphaned }})</h4>
        @foreach(['teacher', 'student', 'guardian', 'accountant'] as $role)
            @if($orphanedRecords[$role]->count() > 0)
                <p><strong>{{ ucfirst($role) }}s:</strong> {{ $orphanedRecords[$role]->count() }} orphaned</p>
            @endif
        @endforeach
        @endif
    </div>
    @endif

    {{-- Spatie Role Synchronization --}}
    @if($missingSpatieRoles->count() > 0 || $mismatchedSpatieRoles->count() > 0 || (isset($multipleSpatieRoles) && $multipleSpatieRoles->count() > 0))
    <div class="section">
        <h3>Spatie Role Synchronization Issues</h3>
        
        @if($missingSpatieRoles->count() > 0)
        <h4>Missing Spatie Roles ({{ $missingSpatieRoles->count() }})</h4>
        <p>Users without Spatie role assignment</p>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Legacy Role</th>
                </tr>
            </thead>
            <tbody>
                @foreach($missingSpatieRoles->take(20) as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role }}</td>
                    </tr>
                @endforeach
                @if($missingSpatieRoles->count() > 20)
                    <tr>
                        <td colspan="4" style="text-align: center; color: #666;">
                            ... and {{ $missingSpatieRoles->count() - 20 }} more (see dashboard for full list)
                        </td>
                    </tr>
                @endif
            </tbody>
        </table>
        @endif

        @if($mismatchedSpatieRoles->count() > 0)
        <h4 style="margin-top: 20px;">Mismatched Spatie Roles ({{ $mismatchedSpatieRoles->count() }})</h4>
        <p>Users with incorrect Spatie role assignment</p>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Legacy Role</th>
                    <th>Spatie Roles</th>
                </tr>
            </thead>
            <tbody>
                @foreach($mismatchedSpatieRoles->take(20) as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role }}</td>
                        <td>{{ $user->roles->pluck('name')->implode(', ') }}</td>
                    </tr>
                @endforeach
                @if($mismatchedSpatieRoles->count() > 20)
                    <tr>
                        <td colspan="5" style="text-align: center; color: #666;">
                            ... and {{ $mismatchedSpatieRoles->count() - 20 }} more (see dashboard for full list)
                        </td>
                    </tr>
                @endif
            </tbody>
        </table>
        @endif

        @if(isset($multipleSpatieRoles) && $multipleSpatieRoles->count() > 0)
        <h4 style="margin-top: 20px;">Multiple Spatie Roles ({{ $multipleSpatieRoles->count() }})</h4>
        <p>Users with more than one Spatie role assigned</p>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Legacy Role</th>
                    <th>Spatie Roles</th>
                </tr>
            </thead>
            <tbody>
                @foreach($multipleSpatieRoles->take(20) as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role }}</td>
                        <td>{{ $user->roles->pluck('name')->implode(', ') }}</td>
                    </tr>
                @endforeach
                @if($multipleSpatieRoles->count() > 20)
                    <tr>
                        <td colspan="5" style="text-align: center; color: #666;">
                            ... and {{ $multipleSpatieRoles->count() - 20 }} more (see dashboard for full list)
                        </td>
                    </tr>
                @endif
            </tbody>
        </table>
        @endif
    </div>
    @endif

    {{-- Database Statistics --}}
    <div class="section">
        <h3>Database Statistics</h3>
        
        <h4>Users by Role</h4>
        <table>
            <thead>
                <tr>
                    <th>Role</th>
                    <th style="text-align: right;">Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($usersByRole as $role => $count)
                    <tr>
                        <td>{{ ucfirst($role) }}</td>
                        <td style="text-align: right;">{{ $count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <h4 style="margin-top: 20px;">Role Record Counts</h4>
        <table>
            <thead>
                <tr>
                    <th>Table</th>
                    <th style="text-align: right;">Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($roleRecordCounts as $role => $count)
                    <tr>
                        <td>{{ ucfirst($role) }}</td>
                        <td style="text-align: right;">{{ $count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    {{-- Recommendations --}}
    <div class="section">
        <h3>Recommendations</h3>
        @if($totalIssues > 0)
            <p><strong>Action Required:</strong></p>
            <ul>
                @if($totalMissing > 0)
                    <li>Run verification: <code>php artisan verify:role-records</code></li>
                    <li>Repair missing records: <code>php artisan verify:role-records --repair --force</code></li>
                @endif
                @if($missingSpatieRoles->count() > 0 || $mismatchedSpatieRoles->count() > 0)
                    <li>Sync Spatie roles: <code>php artisan sync:spatie-roles --repair --force</code></li>
                @endif
                <li>Review and update placeholder values in repaired records</li>
                <li>Monitor system health dashboard regularly</li>
            </ul>
        @else
            <p><strong>System Status: Excellent</strong></p>
            <p>No action required. All systems are operating normally.</p>
            <ul>
                <li>Continue regular monitoring</li>
                <li>Run verification after bulk user imports</li>
                <li>Keep Spatie roles synchronized</li>
            </ul>
        @endif
    </div>

    {{-- Footer --}}
    <div class="footer">
        <p>This report was automatically generated by {{ config('app.name') }} System Health Dashboard</p>
        <p>For support, contact your system administrator</p>
        <p>&copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
    </div>
</body>
</html>
